### ISSUE TITLE
Fonts are not appearing

### ISSUE THREAD

**Issue by yelinaung** [MMAUG/myayphyu#2]
Hi,

I don't see the fonts on the keyboard layout as I think the font needs to be embedded. 

![alt text](https://dl.dropboxusercontent.com/u/2709123/no_kb.png)

I am testing on API 18 . 4.3. Asus Nexus 7.

**Comment by yelinaung** [comment]
I think it can be fixed at `onDraw(Canvas canvas)` by setting typeface to `paint` . 

``` java
if (canvas != null) {           
        paint.setTypeface(Typeface.createFromAsset(mCtx.getAssets(), "fonts/mm3.ttf"));
}
```

where `mCtx` is just a Context.

**Comment by yelinaung** [comment]
Ouch I just got 

```
10-22 09:54:49.365: E/AndroidRuntime(15596): java.lang.RuntimeException: native typeface cannot be made
10-22 09:54:49.365: E/AndroidRuntime(15596):    at android.graphics.Typeface.<init>(Typeface.java:175)
10-22 09:54:49.365: E/AndroidRuntime(15596):    at android.graphics.Typeface.createFromFile(Typeface.java:169)
10-22 09:54:49.365: E/AndroidRuntime(15596):    at com.trhura.android.myayphyu.CandidateView.onDraw(CandidateView.java:214)
```

after setting typeface to the paint. :-(
